# Generated by Django 5.0.4 on 2024-04-30 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBot', '0002_resume_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
