# Generated by Django 5.0.4 on 2024-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBot', '0003_remove_resume_is_active_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-11 13:25:27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'superuser'), (2, 'prouser'), (4, 'basicuser')], default=4),
        ),
    ]
